In [8]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [2]:
# CSV file path
file_path = "psycstat2_assn2_2024.csv"

# CSV file
df = pd.read_csv(file_path)
df.head()

,X,y4,y5,x1,x2,x3,x4,y,c2,id
0,1,5.624415,-2.577023,2.397530,1.258623,-3.951849,-5.539165,5.638557,A,1
1,2,-1.573882,-4.531011,-2.988232,0.080207,-3.894230,-4.871615,-5.904437,B,2
2,3,-2.099296,-1.213603,-3.894230,-5.539165,-3.893745,-4.187285,4.518939,B,3
3,4,2.822516,-3.534985,2.861860,-1.362070,-3.860201,-3.690859,5.520502,B,4
4,5,-6.178302,-8.669524,-3.262579,1.345789,-3.837085,-3.019381,0.701594,A,5

In [4]:
df['d'] = np.where(df['c2'] == "A", 1, np.where(df['c2'] == "B", 0, -99))
df.head()

,X,y4,y5,x1,x2,x3,x4,y,c2,id,d
0,1,5.624415,-2.577023,2.397530,1.258623,-3.951849,-5.539165,5.638557,A,1,1
1,2,-1.573882,-4.531011,-2.988232,0.080207,-3.894230,-4.871615,-5.904437,B,2,0
2,3,-2.099296,-1.213603,-3.894230,-5.539165,-3.893745,-4.187285,4.518939,B,3,0
3,4,2.822516,-3.534985,2.861860,-1.362070,-3.860201,-3.690859,5.520502,B,4,0
4,5,-6.178302,-8.669524,-3.262579,1.345789,-3.837085,-3.019381,0.701594,A,5,1

In [9]:
model = smf.ols('y ~ x1 * d', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.243
Method:                 Least Squares   F-statistic:                     11.58
Date:                Fri, 08 Nov 2024   Prob (F-statistic):           1.52e-06
Time:                        18:31:03   Log-Likelihood:                -303.03
No. Observations:                 100   AIC:                             614.1
Df Residuals:                      96   BIC:                             624.5
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9240      0.760      1.215      0.227      -0.585       2.433
x1            -0.5738      0.316     -1.814      0.073      -1.202       0.054
d             -0.3887      1.040     -0.374      0.709      -2.453       1.676
x1:d           2.1888      0.429      5.104      0.000       1.338       3.040
==============================================================================
Omnibus:                        0.514   Durbin-Watson:                   2.246
Prob(Omnibus):                  0.773   Jarque-Bera (JB):                0.656
Skew:                           0.141   Prob(JB):                        0.720
Kurtosis:                       2.721   Cond. No.                         6.68
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.